### PR TITLE
Fix grade counter on profiles being oddly inaccurate

### PR DESCRIPTION
**Pull request by tsunyoku**

### CODE REVIEW

**Comment by tsunyoku** [comment]
Don’t merge this yet, I realised an error in the grades: it should be ‘x’ not ‘ss’

**Comment by tsunyoku** [comment]
Ok, should be good to go now!

**Comment by alowave223** [comment]
There is an unnecessary parameter here and it also breaks logging, seems like you pr'ed from an old version

**Comment by tsunyoku** [comment]
Probably, it’s taken from my fork which is a quite a few commits old. I’ll wait for @Yo-ru to see this and make the changes he wants.

**Comment by varkaria** [comment]
lgtm! ok i'll merge it

**Comment by varkaria** [comment]
oops i press wrong lmao

**Pull request merged**
